PREFIX smp: <https://github.com/GerhardBalz/semantic-modeling-pizza#>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT ?child ?relation ?parent
WHERE {
    VALUES ?root { smp:FindSuitablePizzasContract }
    ?root prov:wasDerivedFrom* ?child .
    ?child prov:wasDerivedFrom ?parent .
    BIND(prov:wasDerivedFrom AS ?relation)
}
ORDER BY ?child ?relation ?parent
